# NUMPY **LIBRARY**

In [ ]:
import numpy as np #import the library
lst = [2,3,4,5]
arr = np.array(lst)


In [ ]:
arr #return the array

array([2, 3, 4, 5])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
arr.shape #return no of nows and columns

(4,)

In [ ]:
lst1 = [2,3,4,5,6]
lst2 = [6,7,7,8,9]
lst3 = [2,3,5,6,7]
arr1 = np.array([lst1 , lst2 , lst3])

In [ ]:
arr1

array([[2, 3, 4, 5, 6],
       [6, 7, 7, 8, 9],
       [2, 3, 5, 6, 7]])

In [ ]:
arr1.shape

(3, 5)

# INDEXING FOR 1D ARRAY

In [ ]:
arr[::-1] # to reverse the array

array([5, 4, 3, 2])

In [ ]:
arr[1:4] #for a particular range

array([3, 4, 5])

In [ ]:
arr[:-1] #return all elements except the last one

array([2, 3, 4])

In [ ]:
arr[::-2] # element from the last and gap = 2

array([5, 3])

# INDEXING FOR MULTI-D ARRAY

In [ ]:
arr1[:,1] #1st row ke saare elements

array([3, 7, 3])

In [ ]:
arr1[1:,1:3]

array([[7, 7],
       [3, 5]])